name: ltn-bikenetwork-growth-main
channels:
  - conda-forge
dependencies:
  - python=3.12
  - osmnx=1.9.4
  - python-igraph
  - pandas
  - geopandas
  - pyyaml
  - pip
  - owslib
  - matplotlib
  - dill
  - watermark
  - haversine
  - rasterio
  - tqdm
  - geojson
  - geopy
  - shapely
  - ipywidgets
  - numpy
  - networkx
  - fiona
  - tesspy
  - scikit-learn
  - folium
  - pip:
      - opencv-python
      - ipykernel
      - -e .
