name: growbikenet
channels:
  - conda-forge
  - nodefaults
dependencies:
  - affine
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - babel
  - beautifulsoup4
  - bleach
  - blosc
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - dill=0.3.9
  - entrypoints
  - esda=2.7.0
  - exceptiongroup
  - executing
  - fiona=1.10.1
  - fmt
  - folium=0.18.0
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - freexl
  - gdal=3.9.3
  - geographiclib=2.0
  - geojson=3.1.0
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geopy=2.4.1
  - geos=3.13.0
  - geotiff=1.7.3
  - glib=2.82.2
  - glib-tools=2.82.2
  - glpk=5.0
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.14.0
  - h2=4.1.0
  - h3-py=3.7.6
  - h3pandas=0.2.6
  - haversine=2.8.1
  - hdbscan=0.8.39
  - hdf4
  - hdf5
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu
  - idna=3.10
  - imageio=2.37.0
  - importlib_metadata
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kealib=1.5.3
  - kiwisolver=1.4.7
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.3
  - libcrc32c=1.1.2
  - libcurl
  - libdeflate=1.22
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgdal=3.9.3
  - libgdal-core=3.9.3
  - libgdal-fits=3.9.3
  - libgdal-grib=3.9.3
  - libgdal-hdf4=3.9.3
  - libgdal-hdf5=3.9.3
  - libgdal-jp2openjpeg=3.9.3
  - libgdal-kea=3.9.3
  - libgdal-netcdf=3.9.3
  - libgdal-pdf=3.9.3
  - libgdal-pg=3.9.3
  - libgdal-postgisraster=3.9.3
  - libgdal-tiledb=3.9.3
  - libgdal-xls=3.9.3
  - libglib=2.82.2
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgrpc=1.67.1
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libogg=1.3.5
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libpysal=4.12.1
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.0.0
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - lxml=5.3.0
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - minizip=4.0.6
  - mistune=3.0.2
  - momepy=0.8.1
  - mpir=3.0.0
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl
  - osmnx=1.9.4
  - overrides=7.7.0
  - owslib=0.32.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - poppler=24.08.0
  - poppler-data=0.4.12
  - proj=9.5.0
  - prometheus_client
  - prompt-toolkit
  - psutil=6.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pyproj=3.7.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.6
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.6
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - rasterio=1.3.11
  - re2=2024.07.02
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.1
  - rtree=1.3.0
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - send2trash=1.8.3
  - setuptools=75.3.0
  - shapely=2.0.6
  - simplegeneric=0.8.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snuggs=1.4.7
  - soupsieve=2.5
  - spdlog=1.14.1
  - sqlite=3.47.0
  - stack_data=0.6.2
  - tbb=2021.13.0
  - terminado=0.18.1
  - tesspy=0.1.2
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - tiledb=2.26.2
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions
  - typing_extensions
  - typing_utils=0.1.0
  - tzdata=2024b
  - tzlocal=5.3
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.3
  - watermark=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings
  - websocket-client
  - wheel=0.44.0
  - widgetsnbextension
  - xerces-c
  - xorg-kbproto
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-xextproto
  - xorg-xproto
  - xyzservices
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
 

