name: growbikenet
channels:
  - conda-forge
  - nodefaults
dependencies:
  - _r-mutex=1.0.1
  - affine=2.4.0
  - anyio=4.6.2.post1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.0
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.0
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.0
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.1
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - blosc=1.21.6
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - cfitsio=4.4.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.9
  - entrypoints=0.4
  - esda=2.7.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fiona=1.10.1
  - fmt=11.0.2
  - folium=0.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.9.3
  - geographiclib=2.0
  - geojson=3.1.0
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geopy=2.4.1
  - geos=3.13.0
  - geotiff=1.7.3
  - glib=2.82.2
  - glib-tools=2.82.2
  - glpk=5.0
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.14.0
  - h2=4.1.0
  - h3-py=3.7.6
  - h3pandas=0.2.6
  - haversine=2.8.1
  - hdbscan=0.8.39
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imageio=2.37.0
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kealib=1.5.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.3
  - libcrc32c=1.1.2
  - libcurl
  - libdeflate=1.22
  - libexpat=2.6.3
  - libffi=3.4.2
  - libflang=19.1.3
  - libgdal=3.9.3
  - libgdal-core=3.9.3
  - libgdal-fits=3.9.3
  - libgdal-grib=3.9.3
  - libgdal-hdf4=3.9.3
  - libgdal-hdf5=3.9.3
  - libgdal-jp2openjpeg=3.9.3
  - libgdal-kea=3.9.3
  - libgdal-netcdf=3.9.3
  - libgdal-pdf=3.9.3
  - libgdal-pg=3.9.3
  - libgdal-postgisraster=3.9.3
  - libgdal-tiledb=3.9.3
  - libgdal-xls=3.9.3
  - libglib=2.82.2
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgrpc=1.67.1
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libogg=1.3.5
  - libpng=1.6.44
  - libpq=17.0
  - libprotobuf=5.28.2
  - libpysal=4.12.1
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.0.0
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.13.4
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - lxml=5.3.0
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-bwidget=1.9.10
  - m2w64-bzip2=1.0.6
  - m2w64-expat=2.1.1
  - m2w64-fftw=3.3.4
  - m2w64-flac=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-gsl=2.1
  - m2w64-libiconv=1.14
  - m2w64-libjpeg-turbo=1.4.2
  - m2w64-libogg=1.3.2
  - m2w64-libpng=1.6.21
  - m2w64-libsndfile=1.0.26
  - m2w64-libtiff=4.0.6
  - m2w64-libvorbis=1.3.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-libxml2=2.9.3
  - m2w64-mpfr=3.1.4
  - m2w64-pcre2=10.34
  - m2w64-speex=1.2rc2
  - m2w64-speexdsp=1.2rc3
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-tktable=2.10
  - m2w64-wineditline=2.101
  - m2w64-xz=5.2.2
  - m2w64-zlib=1.2.8
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - minizip=4.0.6
  - mistune=3.0.2
  - mkl=2024.2.2
  - momepy=0.8.1
  - mpir=3.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.0
  - osmnx=1.9.4
  - overrides=7.7.0
  - owslib=0.32.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=17.0
  - proj=9.5.0
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pyproj=3.7.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.6
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.6
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pywin32=307
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - r-base=4.1.3
  - rasterio=1.3.11
  - re2=2024.07.02
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.1
  - rpy2=3.5.11
  - rtree=1.3.0
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - send2trash=1.8.3
  - setuptools=75.3.0
  - shapely=2.0.6
  - simplegeneric=0.8.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snuggs=1.4.7
  - soupsieve=2.5
  - spdlog=1.14.1
  - sqlite=3.47.0
  - stack_data=0.6.2
  - tbb=2021.13.0
  - terminado=0.18.1
  - tesspy=0.1.2
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - tiledb=2.26.2
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - tzlocal=5.3
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - watermark=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - et-xmlfile==2.0.0
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - packcircles==0.14
      - pyllist==0.3
      - rustworkx==0.15.1
      - ukcensusapi==1.1.6
      - xlrd==2.0.1

